version: "3.9"

services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks: # <--- AÑADIDO (Opcional, pero bueno para la red interna)
      - user_internal_net # <--- AÑADIDO

  user_service:
    build: .
    container_name: user_service
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "5000:8443"  # <--- CAMBIO 1: De 8000 a 8443 (nuestro puerto SSL)
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@mysql_db/user_db"
    
    volumes: # <--- CAMBIO 2: AÑADIDA ESTA SECCIÓN
      - ../Secure_Channel/certs/user_service/server.crt:/etc/ssl/certs/server.crt:ro
      - ../Secure_Channel/certs/user_service/server.key:/etc/ssl/private/server.key:ro
      
    networks: # <--- CAMBIO 3: AÑADIDA ESTA SECCIÓN
      - user_internal_net # <--- Red para hablar con la BD
      - owlboard-network  # <--- Red para hablar con el API Gateway

volumes:
  mysql_data:

networks: # <--- CAMBIO 3 (continuación): AÑADIDA ESTA SECCIÓN
  user_internal_net: # <--- Define la red interna para la BD
    internal: true
  owlboard-network:  # <--- Define la red externa de los otros servicios
    external: true